name: F4zt Automation

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      paltform: azure
      region: us-east-1
      account: 123123123
      username: ${{secrets.USERNAME}}
      password: $${{secrets.PASSWORD}}

    steps:
      - name: "Show message"
        run: echo "Hello world"

      - name: "Show env variables"
        if: ${{env.paltform=='azure'}}
        run: |
          echo "Este es el valor de platform: ${{ env.paltform }}"
          echo "Este es el valor de region: ${{ env.region }}"
          echo "Este es el valor de account: ${{ env.account }}"
          echo "Esto es un valor de username: ${{env.username}}"
          echo "Esto es un valor de password: ${{env.password}}"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"
          echo "GitHub Actor: ${{github.actor}}"
          echo "GitHub Repository: $GITHUB_REPOSITORY"
